-- =====================================================
-- Digital Family Directory - Seed Data
-- 
-- Seed data has been removed.
-- This project is for real family records only (Mehta Kutumb).
-- No fake/test households or placeholder data are included.
--
-- If you previously ran this migration and have test records
-- (e.g. Sharma / Patel demo entries), run:
--   db/remove_seed_data.sql
-- in your Supabase SQL Editor to purge them.
-- =====================================================

-- No data inserted. Populate using the Submit New Household flow
-- or direct admin inserts for your actual family members.
